import { NextRequest, NextResponse } from "next/server";
import { extract } from "@extractus/article-extractor";
import { createClient } from "@supabase/supabase-js";
import { MongoClient } from "mongodb";
import { convert } from "html-to-text";

const urduDictionary: { [key: string]: string } = {
  summary: "خلاصہ",
  article: "مضمون",
  content: "مواد",
  read: "پڑھیں",
  more: "مزید",
  blog: "بلاگ",
  information: "معلومات",
  technology: "ٹیکنالوجی",
  learn: "سیکھیں",
  about: "کے بارے میں",
  the: "یہ",
  and: "اور",
  is: "ہے",
  are: "ہیں",
  this: "یہ",
  that: "وہ",
  with: "کے ساتھ",
  for: "کے لیے",
  from: "سے",
  to: "کو",
  in: "میں",
  on: "پر",
  at: "میں",
  by: "کے ذریعے",
  of: "کا",
  can: "کر سکتے ہیں",
  will: "کریں گے",
  have: "ہے",
  has: "ہے",
  was: "تھا",
  were: "تھے",
  been: "گیا",
  being: "جا رہا",
  do: "کرتے ہیں",
  does: "کرتا ہے",
  did: "کیا",
  done: "کیا گیا",
  make: "بنانا",
  makes: "بناتا ہے",
  made: "بنایا",
  get: "حاصل کرنا",
  gets: "حاصل کرتا ہے",
  got: "حاصل کیا",
  take: "لینا",
  takes: "لیتا ہے",
  took: "لیا",
  give: "دینا",
  gives: "دیتا ہے",
  gave: "دیا",
  go: "جانا",
  goes: "جاتا ہے",
  went: "گیا",
  come: "آنا",
  comes: "آتا ہے",
  came: "آیا",
  see: "دیکھنا",
  sees: "دیکھتا ہے",
  saw: "دیکھا",
  know: "جاننا",
  knows: "جانتا ہے",
  knew: "جانتا تھا",
  think: "سوچنا",
  thinks: "سوچتا ہے",
  thought: "سوچا",
  work: "کام",
  works: "کام کرتا ہے",
  worked: "کام کیا",
  time: "وقت",
  way: "طریقہ",
  people: "لوگ",
  world: "دنیا",
  life: "زندگی",
  day: "دن",
  year: "سال",
  new: "نیا",
  good: "اچھا",
  great: "عظیم",
  best: "بہترین",
  first: "پہلا",
  last: "آخری",
  long: "لمبا",
  little: "چھوٹا",
  own: "اپنا",
  other: "دوسرا",
  right: "صحیح",
  big: "بڑا",
  high: "اونچا",
  different: "مختلف",
  small: "چھوٹا",
  large: "بڑا",
  next: "اگلا",
  early: "جلدی",
  young: "نوجوان",
  important: "اہم",
  few: "کچھ",
  public: "عوامی",
  bad: "برا",
  same: "ویسا ہی",
  able: "قابل",
  above: "اوپر",
  accept: "قبول کرنا",
  according: "کے مطابق",
  account: "اکاؤنٹ",
  achieve: "حاصل کرنا",
  across: "پار",
  act: "عمل",
  action: "عمل",
  active: "فعال",
  actually: "اصل میں",
  add: "شامل کرنا",
  address: "پتہ",
  admit: "تسلیم کرنا",
  adult: "بالغ",
  advantage: "فائدہ",
  advice: "مشورہ",
  affect: "متاثر کرنا",
  after: "بعد",
  again: "دوبارہ",
  against: "خلاف",
  age: "عمر",
  ago: "پہلے",
  agree: "متفق ہونا",
  ahead: "آگے",
  air: "ہوا",
  all: "سب",
  allow: "اجازت دینا",
  almost: "تقریباً",
  alone: "اکیلا",
  along: "ساتھ",
  already: "پہلے ہی",
  also: "بھی",
  although: "حالانکہ",
  always: "ہمیشہ",
  among: "میں",
  amount: "رقم",
  analysis: "تجزیہ",
  answer: "جواب",
  any: "کوئی",
  anyone: "کوئی بھی",
  anything: "کچھ بھی",
  anywhere: "کہیں بھی",
  appear: "نظر آنا",
  apply: "درخواست دینا",
  approach: "نقطہ نظر",
  area: "علاقہ",
  argue: "بحث کرنا",
  arm: "بازو",
  around: "ارد گرد",
  arrive: "پہنچنا",
  art: "فن",
  as: "جیسے",
  ask: "پوچھنا",
  assume: "فرض کرنا",
  attack: "حملہ",
  attention: "توجہ",
  audience: "سامعین",
  author: "مصنف",
  available: "دستیاب",
  avoid: "بچنا",
  away: "دور",
  baby: "بچہ",
  back: "پیچھے",
  balance: "توازن",
  ball: "گیند",
  bank: "بینک",
  base: "بنیاد",
  be: "ہونا",
  beat: "مارنا",
  beautiful: "خوبصورت",
  because: "کیونکہ",
  become: "بننا",
  before: "پہلے",
  begin: "شروع کرنا",
  behind: "پیچھے",
  believe: "یقین کرنا",
  benefit: "فائدہ",
  better: "بہتر",
  between: "درمیان",
  beyond: "آگے",
  bill: "بل",
  billion: "ارب",
  bit: "تھوڑا",
  black: "کالا",
  blood: "خون",
  blue: "نیلا",
  board: "بورڈ",
  body: "جسم",
  book: "کتاب",
  born: "پیدا ہوا",
  both: "دونوں",
  box: "ڈبہ",
  boy: "لڑکا",
  break: "توڑنا",
  bring: "لانا",
  brother: "بھائی",
  budget: "بجٹ",
  build: "بنانا",
  building: "عمارت",
  business: "کاروبار",
  but: "لیکن",
  buy: "خریدنا",
  call: "کال کرنا",
  camera: "کیمرہ",
  campaign: "مہم",
  car: "گاڑی",
  card: "کارڈ",
  care: "خیال رکھنا",
  career: "کیریئر",
  carry: "اٹھانا",
  case: "کیس",
  catch: "پکڑنا",
  cause: "وجہ",
  cell: "سیل",
  center: "مرکز",
  century: "صدی",
  certain: "یقینی",
  certainly: "یقیناً",
  chair: "کرسی",
  challenge: "چیلنج",
  chance: "موقع",
  change: "تبدیلی",
  character: "کردار",
  charge: "چارج",
  check: "چیک کرنا",
  child: "بچہ",
  choice: "انتخاب",
  choose: "چننا",
  city: "شہر",
  claim: "دعویٰ",
  class: "کلاس",
  clear: "صاف",
  clearly: "واضح طور پر",
  close: "بند کرنا",
  cold: "ٹھنڈا",
  collection: "جمع",
  college: "کالج",
  color: "رنگ",
  common: "عام",
  community: "برادری",
  company: "کمپنی",
  compare: "موازنہ کرنا",
  complete: "مکمل",
  computer: "کمپیوٹر",
  concern: "تشویش",
  condition: "حالت",
  conference: "کانفرنس",
  consider: "غور کرنا",
  continue: "جاری رکھنا",
  control: "کنٹرول",
  cost: "لاگت",
  could: "کر سکتا تھا",
  country: "ملک",
  couple: "جوڑا",
  course: "کورس",
  court: "عدالت",
  cover: "ڈھکنا",
  create: "تخلیق کرنا",
  crime: "جرم",
  culture: "ثقافت",
  current: "موجودہ",
  customer: "صارف",
  cut: "کاٹنا",
  dark: "اندھیرا",
  data: "ڈیٹا",
  daughter: "بیٹی",
  deal: "معاہدہ",
  death: "موت",
  debate: "بحث",
  decade: "دہائی",
  decide: "فیصلہ کرنا",
  decision: "فیصلہ",
  deep: "گہرا",
  defense: "دفاع",
  degree: "ڈگری",
  demand: "طلب",
  describe: "بیان کرنا",
  design: "ڈیزائن",
  despite: "باوجود",
  detail: "تفصیل",
  develop: "ترقی کرنا",
  development: "ترقی",
  die: "مرنا",
  difference: "فرق",
  difficult: "مشکل",
  dinner: "رات کا کھانا",
  direct: "براہ راست",
  direction: "سمت",
  discover: "دریافت کرنا",
  discuss: "بحث کرنا",
  discussion: "گفتگو",
  disease: "بیماری",
  doctor: "ڈاکٹر",
  dog: "کتّا",
  door: "دروازہ",
  down: "نیچے",
  draw: "کشش کرنا",
  dream: "خواب",
  drive: "چلانا",
  drop: "گرانا",
  drug: "دوا",
  during: "دوران",
  each: "ہر ایک",
  eat: "کھانا",
  economic: "معاشی",
  economy: "معیشت",
  education: "تعلیم",
  effect: "اثر",
  effort: "کوشش",
  either: "یا تو",
  election: "انتخابات",
  else: "ورنہ",
  employee: "ملازم",
  end: "ختم",
  energy: "توانائی",
  enjoy: "مزہ لینا",
  enough: "کافی",
  enter: "داخل ہونا",
  entire: "مکمل",
  environment: "ماحول",
  especially: "خاص طور پر",
  establish: "قائم کرنا",
  even: "یہاں تک کہ",
  evening: "شام",
  event: "واقعہ",
  ever: "کبھی",
  every: "ہر",
  everyone: "ہر کوئی",
  everything: "ہر چیز",
  evidence: "ثبوت",
  exactly: "بالکل",
  example: "مثال",
  expect: "توقع کرنا",
  experience: "تجربہ",
  explain: "وضاحت کرنا",
  eye: "آنکھ",
  face: "چہرہ",
  fact: "حقیقت",
  factor: "عنصر",
  fail: "ناکام ہونا",
  fall: "گرنا",
  family: "خاندان",
  far: "دور",
  fast: "تیز",
  father: "والد",
  fear: "خوف",
  feel: "محسوس کرنا",
  feeling: "احساس",
  field: "میدان",
  fight: "لڑائی",
  figure: "شکل",
  fill: "بھرنا",
  film: "فلم",
  final: "آخری",
  finally: "آخر کار",
  find: "تلاش کرنا",
  fine: "ٹھیک",
  finish: "ختم کرنا",
  fire: "آگ",
  firm: "پختہ",
  fish: "مچھلی",
  five: "پانچ",
  floor: "فرش",
  fly: "اڑنا",
  focus: "توجہ دینا",
  follow: "پیروی کرنا",
  food: "کھانا",
  foot: "پاؤں",
  force: "زور",
  foreign: "غیر ملکی",
  forget: "بھولنا",
  form: "شکل",
  former: "سابق",
  forward: "آگے",
  four: "چار",
  free: "آزاد",
  friend: "دوست",
  front: "سامنے",
  full: "مکمل",
  fun: "مزہ",
  future: "مستقبل",
  game: "کھیل",
  garden: "باغ",
  general: "عام",
  girl: "لڑکی",
  glass: "شیشہ",
  goal: "ہدف",
  government: "حکومت",
  green: "سبز",
  ground: "زمین",
  group: "گروپ",
  grow: "بڑھنا",
  growth: "ترقی",
  guess: "اندازہ لگانا",
  hair: "بال",
  half: "آدھا",
  hand: "ہاتھ",
  happen: "ہونا",
  happy: "خوش",
  hard: "سخت",
  head: "سر",
  health: "صحت",
  hear: "سننا",
  heart: "دل",
  heavy: "بھاری",
  help: "مدد",
  here: "یہاں",
  history: "تاریخ",
  hit: "مارنا",
  hold: "پکڑنا",
  home: "گھر",
  hope: "امید",
  hospital: "ہسپتال",
  hot: "گرم",
  hour: "گھنٹہ",
  house: "گھر",
  how: "کیسے",
  however: "تاہم",
  human: "انسان",
  hundred: "سو",
  husband: "شوہر",
  idea: "خیال",
  identify: "شناخت کرنا",
  if: "اگر",
  image: "تصویر",
  imagine: "تصور کرنا",
  impact: "اثر",
  include: "شامل کرنا",
  increase: "اضافہ",
  indeed: "واقعی",
  industry: "صنعت",
  inside: "اندر",
  instead: "اس کی بجائے",
  interest: "دلچسپی",
  international: "بین الاقوامی",
  into: "میں",
  introduce: "متعارف کرانا",
  issue: "مسئلہ",
  item: "آئٹم",
  itself: "خود",
  job: "نوکری",
  join: "شامل ہونا",
  just: "صرف",
  keep: "رکھنا",
  key: "کلیدی",
  kid: "بچہ",
  kind: "قسم",
  kitchen: "باورچی خانہ",
  land: "زمین",
  language: "زبان",
   
  later: "بعد میں",
  laugh: "ہنسنا",
  law: "قانون",
  lead: "رہنمائی کرنا",
  leader: "رہنما",
  leave: "چھوڑنا",
  left: "بائیں",
  less: "کم",
  let: "اجازت دینا",
  letter: "خط",
  level: "سطح",
  lie: "جھوٹ",
  light: "روشنی",
  like: "پسند کرنا",
  likely: "ممکنہ طور پر",
  line: "لائن",
  list: "فہرست",
  listen: "سننا",
  live: "رہنا",
  local: "مقامی",
  look: "دیکھنا",
  lose: "ہارنا",
  loss: "نقصان",
  lot: "بہت",
  love: "محبت",
  low: "کم",
  machine: "مشین",
  main: "اہم",
  maintain: "برقرار رکھنا",
  major: "بڑا",
  man: "آدمی",
  manage: "انتظام کرنا",
  management: "انتظام",
  many: "بہت سے",
  market: "مارکیٹ",
  marriage: "شادی",
  material: "مواد",
  matter: "معاملہ",
  may: "ہو سکتا ہے",
  maybe: "شاید",
  mean: "معنی",
  measure: "پیمائش",
  media: "میڈیا",
  medical: "طبی",
  meet: "ملنا",
  meeting: "ملاقات",
  member: "رکن",
  memory: "یادداشت",
  mention: "ذکر کرنا",
  message: "پیغام",
  method: "طریقہ",
  middle: "درمیان",
  might: "ہو سکتا ہے",
  million: "ملین",
  mind: "دماغ",
  minute: "منٹ",
  miss: "چھوٹنا",
  model: "ماڈل",
  modern: "جدید",
  moment: "لمحہ",
  money: "پیسہ",
  month: "مہینہ",
  morning: "صبح",
  most: "سب سے زیادہ",
  mother: "ماں",
  move: "منتقل کرنا",
  movie: "فلم",
  much: "بہت",
  music: "موسیقی",
  must: "لازمی",
  name: "نام",
  nation: "قوم",
  national: "قومی",
  natural: "قدرتی",
  nature: "فطرت",
  need: "ضرورت",
  network: "نیٹ ورک",
  never: "کبھی نہیں",
  news: "خبریں",
  night: "رات",
  no: "نہیں",
  none: "کوئی نہیں",
  nor: "نہ ہی",
  north: "شمال",
  not: "نہیں",
  note: "نوٹ",
  nothing: "کچھ نہیں",
  notice: "نوٹس",
  now: "اب",
  number: "نمبر",
  offer: "پیشکش",
  office: "دفتر",
  often: "اکثر",
  oil: "تیل",
  old: "پرانا",
  once: "ایک بار",
  one: "ایک",
  only: "صرف",
  open: "کھولنا",
  operation: "آپریشن",
  opportunity: "موقع",
  option: "اختیار",
  or: "یا",
  order: "آرڈر",
  organization: "تنظیم",
  others: "دوسرے",
  our: "ہمارا",
  out: "باہر",
  outside: "باہر",
  over: "اوپر",
   
  owner: "مالک",
  page: "صفحہ",
  pain: "درد",
  paint: "پینٹ",
  paper: "کاغذ",
  parent: "والدین",
  part: "حصہ",
  particular: "خاص",
  partner: "ساتھی",
  party: "پارٹی",
  pass: "گزرنا",
  past: "ماضی",
  patient: "مریض",
  pay: "ادا کرنا",
  peace: "امن",
  perform: "ادا کرنا",
  performance: "کارکردگی",
  perhaps: "شاید",
  period: "دور",
  person: "شخص",
  personal: "ذاتی",
  phone: "فون",
  physical: "جسمانی",
  pick: "چننا",
  picture: "تصویر",
  piece: "ٹکڑا",
  place: "جگہ",
  plan: "منصوبہ",
  plant: "پودا",
  play: "کھیلنا",
  player: "کھلاڑی",
  point: "نقطہ",
  police: "پولیس",
  policy: "پالیسی",
  political: "سیاسی",
  poor: "غریب",
  popular: "مقبول",
  population: "آبادی",
  position: "پوزیشن",
  positive: "مثبت",
  possible: "ممکن",
  power: "طاقت",
  practice: "مشق",
  prepare: "تیاری کرنا",
  present: "موجود",
  president: "صدر",
  pressure: "دباؤ",
  pretty: "خوبصورت",
  price: "قیمت",
  private: "نجی",
  probably: "غالبًا",
  problem: "مسئلہ",
  process: "عمل",
  produce: "پیداوار",
  product: "مصنوعات",
  production: "پیداوار",
  professional: "پیشہ ور",
  program: "پروگرام",
  project: "منصوبہ",
  property: "جائیداد",
  protect: "تحفظ کرنا",
  prove: "ثابت کرنا",
  provide: "فراہم کرنا",
  pull: "کھینچنا",
  purpose: "مقصد",
  push: "دھکیلنا",
  put: "رکھنا",
  quality: "معیار",
  question: "سوال",
  quickly: "جلدی",
  quite: "کافی",
  race: "ریس",
  radio: "ریڈیو",
  raise: "بڑھانا",
  range: "حدود",
  rate: "شرح",
  rather: "بلکہ",
  reach: "پہنچنا",
  
  ready: "تیار",
  real: "حقیقی",
  reality: "حقیقت",
  realize: "احساس کرنا",
  really: "واقعی",
  reason: "وجہ",
  receive: "وصول کرنا",
  recent: "حالیہ",
  recognize: "تسلیم کرنا",
  record: "ریکارڈ",
  red: "سرخ",
  reduce: "کم کرنا",
  reflect: "عکاسی کرنا",
  region: "علاقہ",
  relate: "متعلق ہونا",
  relationship: "رشتہ",
  remain: "رہنا",
  remember: "یاد رکھنا",
  remove: "ہٹانا",
  report: "رپورٹ",
  represent: "نمائندگی کرنا",
  require: "ضرورت ہونا",
  research: "تحقیق",
  resource: "وسائل",
  respect: "عزت",
  respond: "جواب دینا",
  response: "جواب",
  responsibility: "ذمہ داری",
  rest: "آرام",
  result: "نتیجہ",
  return: "واپس آنا",
  reveal: "ظاہر کرنا",
  rich: "امیر",
  ride: "سواری",
  rise: "بڑھنا",
  risk: "خطرہ",
  road: "سڑک",
  rock: "چٹان",
  role: "کردار",
  room: "کمرہ",
  rule: "قاعدہ",
  run: "بھاگنا",
  safe: "محفوظ",
   
  save: "بچانا",
  say: "کہنا",
  school: "سکول",
  science: "سائنس",
  scientist: "سائنسدان",
  score: "اسکور",
  screen: "اسکرین",
  sea: "سمندر",
  search: "تلاش",
  season: "موسم",
  second: "دوسرا",
  security: "سیکیورٹی",
  
  seek: "تلاش کرنا",
  seem: "لگتا ہے",
  sell: "بیچنا",
  send: "بھجنا",
  sense: "احساس",
  series: "سیریز",
  serious: "سنجیدہ",
  serve: "خدمت کرنا",
  service: "خدمت",
  set: "سیٹ",
  several: "کئی",
  share: "بانٹنا",
  she: "وہ",
  short: "مختصر",
  should: "چاہیے",
  show: "دکھانا",
  side: "طرف",
  sign: "نشانی",
  simple: "سادہ",
  simply: "بس",
  since: "تب سے",
  sing: "گانا",
  single: "ایک",
  sister: "بہن",
  sit: "بیٹھنا",
  site: "سائٹ",
  situation: "صورتحال",
  six: "چھ",
  size: "سائز",
  skill: "ہنر",
  sleep: "سونے",
  slow: "آہستہ",
  Small: " چھوٹا",
  smile: "مسکراہٹ",
  so: "تو",
  social: "سماجی",
  society: "معاشرہ",
  solution: "حل",
  some: "کچھ",
  someone: "کوئی",
  something: "کچھ",
  sometimes: "کبھی کبھی",
  son: "بیٹا",
  soon: "جلد",
  sort: "ترتیب",
  sound: "آواز",
  source: "ماخذ",
  south: "جنوب",
  space: "خلا",
  speak: "بولنا",
  special: "خاص",
  specific: "خاص",
  speech: "تقریر",
  spend: "خرچ کرنا",
  sport: "کھیل",
  stand: "کھڑا ہونا",
  star: "ستارہ",
  start: "شروع",
  state: "ریاست",
  statement: "بیان",
  station: "اسٹیشن",
  stay: "رہنا",
  step: "قدم",
  still: "اب بھی",
  stock: "اسٹاک",
  stop: "روکنا",
  store: "اسٹور",
  story: "کہانی",
  strategy: "حکمت عملی",
  street: "گلی",
  strong: "مضبوط",
  student: "طالب علم",
  study: "مطالعہ",
  stuff: "چیز",
  style: "انداز",
  subject: "موضوع",
  success: "کامیابی",
  such: "ایسا",
  suddenly: "اچانک",
  suggest: "تجویز کرنا",
  summer: "موسم گرما",
  support: "حمایت",
  sure: "یقینی",
  surface: "سطح",
  system: "نظام",
  table: "میز",
  talk: "بات کرنا",
  task: "کام",
  tax: "ٹیکس",
  teacher: "استاد",
  team: "ٹیم",
  tell: "بتانا",
  ten: "دس",
  term: "مدت",
  test: "ٹیسٹ",
  than: "سے",
  thank: "شکریہ",
   
  their: "ان کا",
  them: "انہیں",
  then: "پھر",
  there: "وہاں",
  these: "یہ",
  they: "وہ",
  thing: "چیز",
   
  third: "تیسرا",
  those: "وہ",
  though: "اگرچہ",
  thousand: "ہزار",
  three: "تین",
  through: "کے ذریعے",
  throw: "پھینکنا",
  thus: "اس طرح",
  together: "اکٹھے",
  tonight: "آج رات",
  too: "بھی",
  top: "سب سے اوپر",
  total: "کل",
  touch: "چھونا",
  toward: "کی طرف",
  town: "شہر",
  trade: "تجارت",
  traditional: "روایتی",
  train: "ٹرین",
  training: "تربیت",
  travel: "سفر",
  tree: "درخت",
  trouble: "مشکل",
  true: "سچ",
  truth: "سچائی",
  try: "کوشش کرنا",
  turn: "موڑ",
  two: "دو",
  type: "قسم",
  under: "نیچے",
  understand: "سمجھنا",
  unit: "یونٹ",
  until: "تک",
  up: "اوپر",
  upon: "پر",
  us: "ہم",
  use: "استعمال",
  usually: "عام طور پر",
  value: "قدر",
  various: "مختلف",
  very: "بہت",
  view: "نظارہ",
  visit: "ملاقات",
  voice: "آواز",
  vote: "ووٹ",
  wait: "انتظار",
  walk: "چلنا",
  wall: "دیوار",
  want: "چاہنا",
  war: "جنگ",
  watch: "دیکھنا",
  water: "پانی",
  Way: "طریقہ",
  we: "ہم",
  wear: "پہننا",
  week: "ہفتہ",
  weight: "وزن",
  well: "اچھا",
  west: "مغرب",
  what: "کیا",
  whatever: "جو کچھ بھی",
  when: "جب",
  where: "کہاں",
  whether: "چاہے",
  which: "جو",
  while: "جبکہ",
  white: "سفید",
  who: "کون",
  whole: "پورا",
  whom: "جسے",
  whose: "جس کا",
  why: "کیوں",
  wide: "چوڑا",
  wife: "بیوی",
  Will: "خواہش",
  win: "جیتنا",
  wind: "ہوا",
  window: "کھڑکی",
  wish: "خواہش",
  With : "کے ساتھ",
  within: "اندر",
  without: "بغیر",
  woman: "عورت",
  wonder: "حیرت",
  word: "لفظ",
  Work: "کام",
  worker: "مزدور",
  worlds: "دنیا",
  worry: "پریشانی",
  would: "کریں گے",
  write: "لکھنا",
  writer: "مصنف",
  wrong: "غلط",
  yard: " صحن",
  yeah: "ہاں",
  yes: "جی ہاں",
  yet: "ابھی تک",
  you: "آپ",
  your: "آپ کا",
  yourself: "خود",
};

// Simple static summarization
function summarizeContent(content: string): string {
  const text = convert(content, {
    wordwrap: false,
    selectors: [
      { selector: "a", options: { ignoreHref: true } },
      { selector: "img", format: "skip" },
    ],
  });

  const sentences = text.split(/[.!?]+/).filter((s) => s.trim().length > 10);
  let wordCount = 0;
  const selectedSentences: string[] = [];
  
  for (const sentence of sentences) {
    const words = sentence.trim().split(/\s+/).length;
    if (wordCount + words <= 150 && selectedSentences.length < 3) {
      selectedSentences.push(sentence.trim());
      wordCount += words;
    } else {
      break;
    }
  }
  return selectedSentences.join(". ") + (selectedSentences.length > 0 ? "." : "");
}

// Simple Urdu translation
function translateToUrdu(text: string): string {
  let translated = text;
  for (const [en, ur] of Object.entries(urduDictionary)) {
    const regex = new RegExp(`\\b${en}\\b`, "gi");
    translated = translated.replace(regex, ur);
  }
  return translated;
}

export async function POST(req: NextRequest) {
  // Environment variables validation
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_ANON_KEY;
  const mongoUri = process.env.MONGODB_URI;

  console.log("Environment check:");
  console.log("SUPABASE_URL:", supabaseUrl ? "✓ Found" : "✗ Missing");
  console.log("SUPABASE_ANON_KEY:", supabaseKey ? "✓ Found" : "✗ Missing");
  console.log("MONGODB_URI:", mongoUri ? "✓ Found" : "✗ Missing");

  if (!supabaseUrl || !supabaseKey) {
    return NextResponse.json(
      { error: "Supabase configuration is missing (URL or key not found)" },
      { status: 500 }
    );
  }

  if (!mongoUri) {
    return NextResponse.json(
      { error: "MongoDB URI is missing" },
      { status: 500 }
    );
  }

  let mongoClient: MongoClient | null = null;

  try {
    // Parse and validate request body
    const body = await req.json();
    const { url } = body;
    
    if (!url || typeof url !== "string") {
      return NextResponse.json({ error: "Invalid URL provided" }, { status: 400 });
    }

    console.log("Processing URL:", url);

    // Extract article content
    const article = await extract(url);
    console.log("Article extracted:", article ? "✓ Success" : "✗ Failed");
    
    if (!article || !article.content) {
      return NextResponse.json({ error: "Could not extract article content" }, { status: 422 });
    }

    // Generate summary and translation
    const summary = summarizeContent(article.content);
    const urduTranslation = translateToUrdu(summary);

    console.log("Summary generated:", summary ? "✓ Success" : "✗ Failed");
    console.log("Urdu translation:", urduTranslation ? "✓ Success" : "✗ Failed");

    // Initialize Supabase client
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Save to Supabase
    const { error: supabaseError } = await supabase
      .from("summaries")
      .insert({
        url,
        title: article.title || "No title",
        summary,
        urdu_translation: urduTranslation,
        created_at: new Date().toISOString(),
      });

    if (supabaseError) {
      console.error("Supabase error:", supabaseError);
      return NextResponse.json(
        { error: "Failed to save summary to Supabase", details: supabaseError.message },
        { status: 500 }
      );
    }

    console.log("Saved to Supabase: ✓ Success");

    // Connect to MongoDB and save full article
    mongoClient = new MongoClient(mongoUri);
    await mongoClient.connect();
    
    const db = mongoClient.db("blogscraper");
    const articlesCollection = db.collection("articles");

    await articlesCollection.insertOne({
      url,
      title: article.title || "No title",
      content: article.content,
      author: article.author || null,
      source: article.source || null,
      published: article.published || null,
      created_at: new Date(),
    });

    console.log("Saved to MongoDB: ✓ Success");

    // Return successful response
    return NextResponse.json({
      title: article.title || "No title",
      summary,
      urduTranslation,
      author: article.author || null,
      source: article.source || null,
      published: article.published || null,
    });

  } catch (error) {
    console.error("Error processing article:", error);
    return NextResponse.json(
      { 
        error: "Failed to process article", 
        details: error instanceof Error ? error.message : "Unknown error"
      },
      { status: 500 }
    );
  } finally {
    // Always close MongoDB connection
    if (mongoClient) {
      try {
        await mongoClient.close();
        console.log("MongoDB connection closed");
      } catch (closeError) {
        console.error("Error closing MongoDB connection:", closeError);
      }
    }
  }
}